# yaml-language-server: $schema=https://raw.githubusercontent.com/suzuki-shunsuke/pinact/main/json-schema/pinact.json
version: 3

ignore_actions:
  - name: "JackPlowman/reusable-workflows/.github/workflows/common-code-checks.yml"
    ref: "main"
  - name: "JackPlowman/reusable-workflows/.github/workflows/common-clean-caches.yml"
    ref: "main"
  - name: "JackPlowman/reusable-workflows/.github/workflows/common-sync-labels.yml"
    ref: "main"
  - name: "JackPlowman/reusable-workflows/.github/workflows/codeql-analysis.yml"
    ref: "main"
