name: Clean Caches

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  clean-caches:
    name: Clean GitHub Action Caches
    uses: ./.github/workflows/common-clean-caches.yml
    secrets:
      workflow_github_token: ${{ secrets.GITHUB_TOKEN }}
