name: Clean Caches

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

permissions: {}

jobs:
  clean-caches:
    name: Clean GitHub Action Caches
    uses: JackPlowman/reusable-workflows/common-clean-caches.yml@${{ github.ref }}
    permissions:
      contents: read
    secrets:
      workflow_github_token: ${{ secrets.GH_TOKEN }}
