name: "Common Code Checks"

on:
  workflow_call:
    secrets:
      workflow_github_token:
        required: true
        description: "GitHub token for workflow"

# zizmor: ignore[concurrency-limits] only GitHub can trigger this workflow

permissions:
  contents: read

env:
  FORCE_COLOR: 1

jobs:
  check-justfile-format:
    name: Check Justfile Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up Just
        uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4.0.0
      - name: Check Justfile Format
        run: just format-check

  check-markdown-links:
    name: Check Markdown links
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # to create PR review comments
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Check Markdown links
        uses: UmbrellaDocs/action-linkspector@568ec8d29fa92b31fd9ea5381e155c51e922af83 # v1.5.5
        with:
          github_token: ${{ secrets.workflow_github_token }} # zizmor: ignore[secrets-outside-env]
          config_file: .github/tool-configurations/.linkspector.yml
          reporter: github-pr-review
          fail_on_error: true
          filter_mode: nofilter
          show_stats: true

  pinact-check:
    name: Pinact Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Check actions are pinned (with config)
        if: ${{ hashFiles('.github/tool-configurations/pinact.yml') != '' }}
        uses: suzuki-shunsuke/pinact-action@896d595f299e71d65b9d28349d6956abe144390a # v3.0.0
        with:
          skip_push: "true"
        env:
          PINACT_CONFIG: .github/tool-configurations/pinact.yml
      - name: Check actions are pinned (without config)
        if: ${{ hashFiles('.github/tool-configurations/pinact.yml') == '' }}
        uses: suzuki-shunsuke/pinact-action@896d595f299e71d65b9d28349d6956abe144390a # v3.0.0
        with:
          skip_push: "true"

  prek-check:
    name: "Validate Prek Git Hooks Configuration"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up Just
        uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4.0.0
      - name: Run Prek Action
        uses: j178/prek-action@4e14d07f9231acabce116ccfca13b13dd9755ece # v3.0.0
        with:
          prek-version: "0.4.8"
          install-only: "true"
      - name: Prek Check
        run: just prek-check

  run-actionlint:
    name: Check GitHub Actions with Actionlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Run Actionlint
        uses: docker://rhysd/actionlint:1.7.12 # zizmor: ignore[unpinned-uses]
        with:
          args: -color

  run-editorconfig-checker:
    name: Check File Formats with EditorConfig Checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Run EditorConfig Checker
        uses: docker://mstruebing/editorconfig-checker:v3.6.1 # zizmor: ignore[unpinned-uses]
        with:
          args: editorconfig-checker -color -format=github-actions

  run-gitleaks:
    name: Check for Secrets with Gitleaks
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # for annotations
      security-events: write # to create secret scanning alerts
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@e0c47f4f8be36e29cdc102c57e68cb5cbf0e8d1e # v3.0.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GITLEAKS_ENABLE_UPLOAD_ARTIFACT: "true"
          GITLEAKS_NOTIFY_USER_LIST: "@JackPlowman"
      - name: Upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@cdf488f595d80d6e07e03d4674febd5ab45fa938 # v4.37.9
        with:
          sarif_file: results.sarif

  run-grype:
    name: Check for Vulnerabilities with Grype
    runs-on: ubuntu-latest
    permissions:
      security-events: write # to create secret scanning alerts
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Scan current project
        id: scan
        uses: anchore/scan-action@27805bf3b4e84b4a5c980df22ed233c00390a439 # v7.4.2
        with:
          path: "."
        continue-on-error: true
      - name: Upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@cdf488f595d80d6e07e03d4674febd5ab45fa938 # v4.37.9
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
      - name: Scan current project
        uses: anchore/scan-action@27805bf3b4e84b4a5c980df22ed233c00390a439 # v7.4.2
        with:
          path: "."

  run-markdownlint:
    name: "Check Markdown Files with Markdownlint"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Run Markdownlint
        uses: DavidAnson/markdownlint-cli2-action@21c1be1b93ad9ed58fa840aacc3f279cde2a72ff # v24.2.0
        with:
          config: ".github/tool-configurations/.markdownlint-cli2.jsonc"
          globs: |
            README
            *.md
            **/*.md

  run-prek:
    name: "Run Prek pre-commit hook checks"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up Just
        uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4.0.0
      - name: Run Prek Action
        uses: j178/prek-action@4e14d07f9231acabce116ccfca13b13dd9755ece # v3.0.0
        with:
          prek-version: "0.4.8"

  run-prettier:
    name: "Check Code Formatting with Prettier"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js environment
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      - name: Install Prettier
        run: npm install -g prettier@3.9.6 # zizmor: ignore[adhoc-packages]
      - name: Set up Just
        uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4.0.0
      - name: Check Code Formatting with Prettier
        run: just prettier-check

  run-trivy:
    name: "Check Vulnerabilities, Secrets, Misconfigurations, and Licenses with Trivy"
    runs-on: ubuntu-latest
    permissions:
      security-events: write # to create secret scanning alerts
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          scan-type: "fs"
          scan-ref: "."
          trivy-config: .github/tool-configurations/trivy.yml
          format: "sarif"
          output: "trivy-results.sarif"
          version: v0.71.2
      - name: Upload Trivy SARIF report
        uses: github/codeql-action/upload-sarif@cdf488f595d80d6e07e03d4674febd5ab45fa938 # v4.37.9
        with:
          sarif_file: trivy-results.sarif

  run-trufflehog:
    name: Check for Secrets with TruffleHog
    runs-on: ubuntu-latest
    permissions:
      security-events: write # to create secret scanning alerts
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@363923b901c911a9164f50b6c423f47c15372b1c # v3.97.4
        with:
          extra_args: --results=verified,unknown

  run-yamllint:
    name: "Check YAML Files with Yamllint"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: "Yamllint"
        uses: karancode/yamllint-github-action@4052d365f09b8d34eb552c363d1141fd60e2aeb2 # v3.0.0
        with:
          yamllint_file_or_dir: "."
          yamllint_config_filepath: ".github/tool-configurations/.yaml-lint.yml"
          yamllint_strict: true
          yamllint_comment: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.workflow_github_token }} # zizmor: ignore[secrets-outside-env]

  run-zizmor:
    name: Check GitHub Actions with zizmor
    runs-on: ubuntu-latest
    permissions:
      actions: read # to read actions
      security-events: write # to create secret scanning alerts
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Run zizmor 🌈
        uses: zizmorcore/zizmor-action@3dc1ecc9bcb9e94e9b2c709687979e1298497054 # v0.6.2
        with:
          persona: auditor
          version: 1.28.0
