name: "Pull Request Tasks"

on:
  pull_request:
    types: [opened, edited, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  common-pull-request-tasks:
    name: Common Pull Request Tasks
    permissions:
      pull-requests: write # For writing labels and comments on PRs
    uses: ./.github/workflows/common-pull-request-tasks.yml
    secrets:
      workflow_github_token: ${{ secrets.GITHUB_TOKEN }}
