name: Create Release

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/common-*.yml"
      - ".github/workflows/codeql-analysis.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to create releases

    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Generate release tag
        id: generate_release_tag
        uses: amitsingh-007/next-release-tag@ccca26be97e8a3e33f50ec71a42bdd596cbc249f # v6.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: "v"
          tag_template: "yyyy.mm.dd.i"
      - name: Create Release with GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEXT_RELEASE_TAG: ${{ steps.generate_release_tag.outputs.next_release_tag }}
        run: gh release create "$NEXT_RELEASE_TAG" --title "Release $NEXT_RELEASE_TAG" --generate-notes
