name: "Sync labels"

on:
  push:
    branches:
      - main
    paths:
      - .github/tool-configurations/labels.yml
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  configure-labels:
    name: Configure Labels
    permissions:
      contents: read
      pull-requests: write # For writing labels to the repository
    uses: ./.github/workflows/common-sync-labels.yml
    secrets:
      workflow_github_token: ${{ secrets.GITHUB_TOKEN }}
