name: "Sync labels"

on:
  push:
    branches:
      - main
    paths:
      - .github/tool-configurations/labels.yml
  workflow_dispatch:

permissions: {}

jobs:
  configure-labels:
    name: Configure Labels
    permissions:
      contents: read
      pull-requests: write
    uses: ./.github/workflows/common-sync-labels.yml
    secrets:
      workflow_github_token: ${{ secrets.GITHUB_TOKEN }}
